//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_loader.dart'; // part '_w_loader_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WLoaderMakeup {
  //
  //
  //

  Color? backgroundColor;
  Color? color;
  Color? errorColor;
  double? size;
  double? strokeWidth;
  Color? successColor;
  Animation<Color?>? valueColor;

  //
  //
  //

  WLoaderMakeup({
    this.backgroundColor,
    this.color,
    this.errorColor,
    this.size,
    this.strokeWidth,
    this.successColor,
    this.valueColor,
  });

  //
  //
  //

  WLoaderMakeup copyWith({
    Color? backgroundColor,
    Color? color,
    Color? errorColor,
    double? size,
    double? strokeWidth,
    Color? successColor,
    Animation<Color?>? valueColor,
  }) {
    return WLoaderMakeup(
      backgroundColor: backgroundColor ?? this.backgroundColor,
      color: color ?? this.color,
      errorColor: errorColor ?? this.errorColor,
      size: size ?? this.size,
      strokeWidth: strokeWidth ?? this.strokeWidth,
      successColor: successColor ?? this.successColor,
      valueColor: valueColor ?? this.valueColor,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWLoaderMakeup = WLoaderMakeup Function();
