#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Flutter Plus
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_flutter_plus
publish_to: none
version: 0.10.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'
  flutter: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependency_overrides:

  # xyz_utils:
  #   path: ../xyz_utils

  # xyz_pod:
  #   path: ../xyz_pod

  # xyz_gen:
  #   path: ../xyz_gen

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  async:
  connectivity_plus:
  crypto:
  device_info_plus:
  encrypt:
  equatable:
  go_router:
  html:
  http:
  meta:
  shared_preferences:
  url_launcher:

  #
  
  flutter_svg:

  xyz_pod: ^0.7.2

  xyz_gen: ^0.19.0

  xyz_config:
    git:
      url: https://github.com/robmllze/xyz_config.git

  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints:

## -----------------------------------------------------------------------------

flutter: