##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_flutter_plus
description: This package provides a set of utilities that are commonly used in Flutter apps.
repository: https://github.com/robmllze/xyz_flutter_plus
version: 0.43.6

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  xyz_config: ^0.28.1
  xyz_gen_annotations: ^0.24.1
  xyz_pod: ^0.29.0
  xyz_utils: ^0.53.0

  async: ^2.11.0
  connectivity_plus: ^6.0.1
  crypto: ^3.0.3
  device_info_plus: ^10.0.1
  equatable: ^2.0.5
  go_router: ^13.2.1
  html: ^0.15.4
  http: ^1.2.1
  meta: ^1.11.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^3.0.1
