//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_chip.dart'; // part '_w_chip_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WChipMakeup {
  //
  //
  //

  TextStyle? Function(WChipOptions)? textStyleBuilder;
  BoxDecoration? Function(WChipOptions)? decorationBuilder;
  BorderRadius? borderRadius;
  Color? colorSelected;
  Color? colorSelectedDisabled;
  Color? colorUnselected;
  Color? colorUnselectedDisabled;
  EdgeInsets? padding;
  TextStyle? textStyleSelected;
  TextStyle? textStyleSelectedDisabled;
  TextStyle? textStyleUnselected;
  TextStyle? textStyleUnselectedDisabled;

  //
  //
  //

  WChipMakeup({
    this.textStyleBuilder,
    this.decorationBuilder,
    this.borderRadius,
    this.colorSelected,
    this.colorSelectedDisabled,
    this.colorUnselected,
    this.colorUnselectedDisabled,
    this.padding,
    this.textStyleSelected,
    this.textStyleSelectedDisabled,
    this.textStyleUnselected,
    this.textStyleUnselectedDisabled,
  });

  //
  //
  //

  WChipMakeup copyWith({
    TextStyle? Function(WChipOptions)? textStyleBuilder,
    BoxDecoration? Function(WChipOptions)? decorationBuilder,
    BorderRadius? borderRadius,
    Color? colorSelected,
    Color? colorSelectedDisabled,
    Color? colorUnselected,
    Color? colorUnselectedDisabled,
    EdgeInsets? padding,
    TextStyle? textStyleSelected,
    TextStyle? textStyleSelectedDisabled,
    TextStyle? textStyleUnselected,
    TextStyle? textStyleUnselectedDisabled,
  }) {
    return WChipMakeup(
      textStyleBuilder: textStyleBuilder ?? this.textStyleBuilder,
      decorationBuilder: decorationBuilder ?? this.decorationBuilder,
      borderRadius: borderRadius ?? this.borderRadius,
      colorSelected: colorSelected ?? this.colorSelected,
      colorSelectedDisabled:
          colorSelectedDisabled ?? this.colorSelectedDisabled,
      colorUnselected: colorUnselected ?? this.colorUnselected,
      colorUnselectedDisabled:
          colorUnselectedDisabled ?? this.colorUnselectedDisabled,
      padding: padding ?? this.padding,
      textStyleSelected: textStyleSelected ?? this.textStyleSelected,
      textStyleSelectedDisabled:
          textStyleSelectedDisabled ?? this.textStyleSelectedDisabled,
      textStyleUnselected: textStyleUnselected ?? this.textStyleUnselected,
      textStyleUnselectedDisabled:
          textStyleUnselectedDisabled ?? this.textStyleUnselectedDisabled,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWChipMakeup = WChipMakeup Function();
