//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_icon.dart'; // part '_w_icon_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WIconMakeup {
  //
  //
  //

  IconData? icon;
  Color? color;
  double? size;
  BoxDecoration? decoration;

  //
  //
  //

  WIconMakeup({
    this.icon,
    this.color,
    this.size,
    this.decoration,
  });

  //
  //
  //

  WIconMakeup copyWith({
    IconData? icon,
    Color? color,
    double? size,
    BoxDecoration? decoration,
  }) {
    return WIconMakeup(
      icon: icon ?? this.icon,
      color: color ?? this.color,
      size: size ?? this.size,
      decoration: decoration ?? this.decoration,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWIconMakeup = WIconMakeup Function();
