//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of "w_scrollable.dart"; // part '_w_scrollable_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WScrollableMakeup {
  //
  //
  //

  EdgeInsets? insidePadding;
  bool? thumbVisibility;
  EdgeInsets? outsidePadding;
  WScrollbarStyle? style;

  //
  //
  //

  WScrollableMakeup({
    this.insidePadding,
    this.thumbVisibility,
    this.outsidePadding,
    this.style,
  });

  //
  //
  //

  WScrollableMakeup copyWith({
    EdgeInsets? insidePadding,
    bool? thumbVisibility,
    EdgeInsets? outsidePadding,
    WScrollbarStyle? style,
  }) {
    return WScrollableMakeup(
      insidePadding: insidePadding ?? this.insidePadding,
      thumbVisibility: thumbVisibility ?? this.thumbVisibility,
      outsidePadding: outsidePadding ?? this.outsidePadding,
      style: style ?? this.style,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWScrollableMakeup = WScrollableMakeup Function();
