//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_dot.dart'; // part '_w_dot_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WDotMakeup {
  //
  //
  //

  TextStyle? textStyle;
  Color? backgroundColor;
  double? height;
  double? addedWidth;
  Border? border;
  List<BoxShadow>? shadow;

  //
  //
  //

  WDotMakeup({
    this.textStyle,
    this.backgroundColor,
    this.height,
    this.addedWidth,
    this.border,
    this.shadow,
  });

  //
  //
  //

  WDotMakeup copyWith({
    TextStyle? textStyle,
    Color? backgroundColor,
    double? height,
    double? addedWidth,
    Border? border,
    List<BoxShadow>? shadow,
  }) {
    return WDotMakeup(
      textStyle: textStyle ?? this.textStyle,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      height: height ?? this.height,
      addedWidth: addedWidth ?? this.addedWidth,
      border: border ?? this.border,
      shadow: shadow ?? this.shadow,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWDotMakeup = WDotMakeup Function();
