//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_toast.dart'; // part '_w_toast_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WToastMakeup {
  //
  //
  //

  TextStyle? actionTextStyle;
  Color? backgroundColor;
  Color? barColor;
  Widget? closeIcon;
  TextStyle? dateTextStyle;
  TextStyle? descriptionTextStyle;
  Widget? icon;
  Radius? radius;
  List<BoxShadow>? shadow;
  TextStyle? titleTextStyle;

  //
  //
  //

  WToastMakeup({
    this.actionTextStyle,
    this.backgroundColor,
    this.barColor,
    this.closeIcon,
    this.dateTextStyle,
    this.descriptionTextStyle,
    this.icon,
    this.radius,
    this.shadow,
    this.titleTextStyle,
  });

  //
  //
  //

  WToastMakeup copyWith({
    TextStyle? actionTextStyle,
    Color? backgroundColor,
    Color? barColor,
    Widget? closeIcon,
    TextStyle? dateTextStyle,
    TextStyle? descriptionTextStyle,
    Widget? icon,
    Radius? radius,
    List<BoxShadow>? shadow,
    TextStyle? titleTextStyle,
  }) {
    return WToastMakeup(
      actionTextStyle: actionTextStyle ?? this.actionTextStyle,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      barColor: barColor ?? this.barColor,
      closeIcon: closeIcon ?? this.closeIcon,
      dateTextStyle: dateTextStyle ?? this.dateTextStyle,
      descriptionTextStyle: descriptionTextStyle ?? this.descriptionTextStyle,
      icon: icon ?? this.icon,
      radius: radius ?? this.radius,
      shadow: shadow ?? this.shadow,
      titleTextStyle: titleTextStyle ?? this.titleTextStyle,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWToastMakeup = WToastMakeup Function();
