//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'components/all_components.g.dart';
export 'components/scalable/w_circle_button.dart';
export 'components/scalable/w_custom_scroll_bar.dart';
export 'components/scalable/w_horizontal_separator.dart';
export 'components/scalable/w_icon_button.dart';
export 'components/scalable/w_inline_text.dart';
export 'components/scalable/w_search_bar_with_actions_layout.dart';
export 'components/scalable_with_makeups/w_scrollable/w_scrollable.dart';
export 'components/scalable_with_makeups/w_toast/w_toast.dart';
export 'components/w_action.dart';
export 'components/w_activity_feed.dart';
export 'components/w_animated_blur.dart';
export 'components/w_animated_fade.dart';
export 'components/w_animated_scale.dart';
export 'components/w_animated_size.dart';
export 'components/w_animated_slide.dart';
export 'components/w_autocompleter_text_field.dart';
export 'components/w_blur.dart';
export 'components/w_circle.dart';
export 'components/w_clear_button.dart';
export 'components/w_collapsable.dart';
export 'components/w_column.dart';
export 'components/w_facade.dart';
export 'components/w_field.dart';
export 'components/w_global_overlay.dart';
export 'components/w_hide_keyboard_on_tap.dart';
export 'components/w_hover_scaler.dart';
export 'components/w_indented_json.dart';
export 'components/w_intrinsic_column.dart';
export 'components/w_intrinsic_row.dart';
export 'components/w_main_layout.dart';
export 'components/w_navigation_controls.dart';
export 'components/w_omni_scrollable.dart';
export 'components/w_rebuilder.dart';
export 'components/w_row.dart';
export 'components/w_scrollbar.dart';
export 'components/w_slider.dart';
export 'components/w_spinner.dart';
export 'components/w_stateful_builder.dart';
export 'components/w_tap_detector.dart';
export 'components/w_widget_calculator.dart';
export 'utils/all_utils.g.dart';
export 'utils/app_layout.dart';
export 'utils/app_scale.dart';
export 'utils/color/color_blenders.dart';
export 'utils/color/color_mixer.dart';
export 'utils/color/color_utils.dart';
export 'utils/color/common_palette.dart';
export 'utils/color/dynamic_palette.dart';
export 'utils/color/example_flat_colors.dart';
export 'utils/color/example_palettes/bronze_palette.dart';
export 'utils/color/example_palettes/medi_palette.dart';
export 'utils/color/single_palette.dart';
export 'utils/common_widths_and_heights.dart';
export 'utils/current_platform.dart';
export 'utils/hidden_scrollbar_scroll_behavior.dart';
export 'utils/image_builder.dart';
export 'utils/internet_connection_checker.dart';
export 'utils/keyboard_observer.dart';
export 'utils/lazy.dart';
export 'utils/pin_manager.dart';
export 'utils/secure_shared_preferences.dart';
export 'utils/text_style_utils.dart';
export 'utils/to_tappable_text.dart';
export 'utils/transparent_page.dart';
export 'utils/widget_visibility_manager.dart';
