//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_panel.dart'; // part '_w_panel_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WPanelMakeup {
  //
  //
  //

  Color? color;
  double? padding;
  double? defaultWidth;
  double? defaultHeight;
  BorderRadius? borderRadius;
  List<BoxShadow>? boxShadow;

  //
  //
  //

  WPanelMakeup({
    this.color,
    this.padding,
    this.defaultWidth,
    this.defaultHeight,
    this.borderRadius,
    this.boxShadow,
  });

  //
  //
  //

  WPanelMakeup copyWith({
    Color? color,
    double? padding,
    double? defaultWidth,
    double? defaultHeight,
    BorderRadius? borderRadius,
    List<BoxShadow>? boxShadow,
  }) {
    return WPanelMakeup(
      color: color ?? this.color,
      padding: padding ?? this.padding,
      defaultWidth: defaultWidth ?? this.defaultWidth,
      defaultHeight: defaultHeight ?? this.defaultHeight,
      borderRadius: borderRadius ?? this.borderRadius,
      boxShadow: boxShadow ?? this.boxShadow,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWPanelMakeup = WPanelMakeup Function();
