//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_text_field.dart'; // part '_w_text_field_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WTextFieldMakeup {
  //
  //
  //

  Color? cursorColor;
  BoxDecoration? decoration;
  TWTextFieldMakeupFilter? disabledErrorMakeupFilter;
  TWTextFieldMakeupFilter? disabledMakeupFilter;
  Widget? Function(WTextFieldEvent)? errorBuilder;
  TWTextFieldMakeupFilter? errorMakeupFilter;
  bool? expands;
  TWTextFieldMakeupFilter? finalMakeupFilter;
  Widget? Function(WTextFieldEvent)? hintBuilder;
  List<TextInputFormatter>? inputFormatters;
  EdgeInsets? insidePadding;
  TextInputType? keyboardType;
  Widget? Function(WTextFieldEvent)? leftWidgetBuilder;
  int? maxLines;
  int? minLines;
  EdgeInsets? outsidePadding;
  Widget? Function(WTextFieldEvent)? rightWidgetBuilder;
  Color? selectionColor;
  TextAlign? textAlign;
  TextStyle? textStyle;
  Widget? Function(WTextFieldEvent)? titleBuilder;
  Widget? Function(WTextFieldEvent)? titleDotBuilder;

  //
  //
  //

  WTextFieldMakeup({
    this.cursorColor,
    this.decoration,
    this.disabledErrorMakeupFilter,
    this.disabledMakeupFilter,
    this.errorBuilder,
    this.errorMakeupFilter,
    this.expands,
    this.finalMakeupFilter,
    this.hintBuilder,
    this.inputFormatters,
    this.insidePadding,
    this.keyboardType,
    this.leftWidgetBuilder,
    this.maxLines,
    this.minLines,
    this.outsidePadding,
    this.rightWidgetBuilder,
    this.selectionColor,
    this.textAlign,
    this.textStyle,
    this.titleBuilder,
    this.titleDotBuilder,
  });

  //
  //
  //

  WTextFieldMakeup copyWith({
    Color? cursorColor,
    BoxDecoration? decoration,
    TWTextFieldMakeupFilter? disabledErrorMakeupFilter,
    TWTextFieldMakeupFilter? disabledMakeupFilter,
    Widget? Function(WTextFieldEvent)? errorBuilder,
    TWTextFieldMakeupFilter? errorMakeupFilter,
    bool? expands,
    TWTextFieldMakeupFilter? finalMakeupFilter,
    Widget? Function(WTextFieldEvent)? hintBuilder,
    List<TextInputFormatter>? inputFormatters,
    EdgeInsets? insidePadding,
    TextInputType? keyboardType,
    Widget? Function(WTextFieldEvent)? leftWidgetBuilder,
    int? maxLines,
    int? minLines,
    EdgeInsets? outsidePadding,
    Widget? Function(WTextFieldEvent)? rightWidgetBuilder,
    Color? selectionColor,
    TextAlign? textAlign,
    TextStyle? textStyle,
    Widget? Function(WTextFieldEvent)? titleBuilder,
    Widget? Function(WTextFieldEvent)? titleDotBuilder,
  }) {
    return WTextFieldMakeup(
      cursorColor: cursorColor ?? this.cursorColor,
      decoration: decoration ?? this.decoration,
      disabledErrorMakeupFilter:
          disabledErrorMakeupFilter ?? this.disabledErrorMakeupFilter,
      disabledMakeupFilter: disabledMakeupFilter ?? this.disabledMakeupFilter,
      errorBuilder: errorBuilder ?? this.errorBuilder,
      errorMakeupFilter: errorMakeupFilter ?? this.errorMakeupFilter,
      expands: expands ?? this.expands,
      finalMakeupFilter: finalMakeupFilter ?? this.finalMakeupFilter,
      hintBuilder: hintBuilder ?? this.hintBuilder,
      inputFormatters: inputFormatters ?? this.inputFormatters,
      insidePadding: insidePadding ?? this.insidePadding,
      keyboardType: keyboardType ?? this.keyboardType,
      leftWidgetBuilder: leftWidgetBuilder ?? this.leftWidgetBuilder,
      maxLines: maxLines ?? this.maxLines,
      minLines: minLines ?? this.minLines,
      outsidePadding: outsidePadding ?? this.outsidePadding,
      rightWidgetBuilder: rightWidgetBuilder ?? this.rightWidgetBuilder,
      selectionColor: selectionColor ?? this.selectionColor,
      textAlign: textAlign ?? this.textAlign,
      textStyle: textStyle ?? this.textStyle,
      titleBuilder: titleBuilder ?? this.titleBuilder,
      titleDotBuilder: titleDotBuilder ?? this.titleDotBuilder,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWTextFieldMakeup = WTextFieldMakeup Function();
