//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import 'package:flutter/widgets.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class MToastMakeup {
  //
  //
  //

  TextStyle? actionTextStyle;
  Color? backgroundColor;
  Color? barColor;
  Widget? closeIcon;
  TextStyle? dateTextStyle;
  TextStyle? descriptionTextStyle;
  Widget? icon;
  Radius? radius;
  List<BoxShadow>? shadow;
  TextStyle? titleTextStyle;

  //
  //
  //

  MToastMakeup({
    this.actionTextStyle,
    this.backgroundColor,
    this.barColor,
    this.closeIcon,
    this.dateTextStyle,
    this.descriptionTextStyle,
    this.icon,
    this.radius,
    this.shadow,
    this.titleTextStyle,
  });

  //
  //
  //

  MToastMakeup copyWith({
    TextStyle? actionTextStyle,
    Color? backgroundColor,
    Color? barColor,
    Widget? closeIcon,
    TextStyle? dateTextStyle,
    TextStyle? descriptionTextStyle,
    Widget? icon,
    Radius? radius,
    List<BoxShadow>? shadow,
    TextStyle? titleTextStyle,
  }) {
    return MToastMakeup(
      actionTextStyle: actionTextStyle ?? this.actionTextStyle,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      barColor: barColor ?? this.barColor,
      closeIcon: closeIcon ?? this.closeIcon,
      dateTextStyle: dateTextStyle ?? this.dateTextStyle,
      descriptionTextStyle: descriptionTextStyle ?? this.descriptionTextStyle,
      icon: icon ?? this.icon,
      radius: radius ?? this.radius,
      shadow: shadow ?? this.shadow,
      titleTextStyle: titleTextStyle ?? this.titleTextStyle,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWToastMakeup = MToastMakeup Function();

const kWToastMakeupProperties = <String, String>{
  'actionTextStyle': 'TextStyle?',
  'backgroundColor': 'Color?',
  'barColor': 'Color?',
  'closeIcon': 'Widget?',
  'dateTextStyle': 'TextStyle?',
  'descriptionTextStyle': 'TextStyle?',
  'icon': 'Widget?',
  'radius': 'Radius?',
  'shadow': 'List<BoxShadow>?',
  'titleTextStyle': 'TextStyle?',
};
