//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_radio.dart'; // part '_w_radio_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WRadioMakeup {
  //
  //
  //

  Color? disabledBorderColor;
  Color? disabledSelectedFillColor;
  Color? disabledUnselectedFillColor;
  Color? borderColor;
  Color? selectedFillColor;
  Color? unselectedFillColor;
  BorderRadius? borderRadius;
  double? borderThickness;
  TextStyle? elementStyle;
  TextStyle? errorStyle;
  BorderRadius? innerBorderRadius;
  EdgeInsets? innerPadding;
  bool? isChildrenAfter;
  bool? isChildrenBefore;
  Icon? selectedIcon;
  BoxShape? shape;
  double? size;
  SizedBox? spacer;
  Widget? Function(String?)? titleBuilder;
  Widget? Function(bool?)? titleDotBuilder;

  //
  //
  //

  WRadioMakeup({
    this.disabledBorderColor,
    this.disabledSelectedFillColor,
    this.disabledUnselectedFillColor,
    this.borderColor,
    this.selectedFillColor,
    this.unselectedFillColor,
    this.borderRadius,
    this.borderThickness,
    this.elementStyle,
    this.errorStyle,
    this.innerBorderRadius,
    this.innerPadding,
    this.isChildrenAfter,
    this.isChildrenBefore,
    this.selectedIcon,
    this.shape,
    this.size,
    this.spacer,
    this.titleBuilder,
    this.titleDotBuilder,
  });

  //
  //
  //

  WRadioMakeup copyWith({
    Color? disabledBorderColor,
    Color? disabledSelectedFillColor,
    Color? disabledUnselectedFillColor,
    Color? borderColor,
    Color? selectedFillColor,
    Color? unselectedFillColor,
    BorderRadius? borderRadius,
    double? borderThickness,
    TextStyle? elementStyle,
    TextStyle? errorStyle,
    BorderRadius? innerBorderRadius,
    EdgeInsets? innerPadding,
    bool? isChildrenAfter,
    bool? isChildrenBefore,
    Icon? selectedIcon,
    BoxShape? shape,
    double? size,
    SizedBox? spacer,
    Widget? Function(String?)? titleBuilder,
    Widget? Function(bool?)? titleDotBuilder,
  }) {
    return WRadioMakeup(
      disabledBorderColor: disabledBorderColor ?? this.disabledBorderColor,
      disabledSelectedFillColor:
          disabledSelectedFillColor ?? this.disabledSelectedFillColor,
      disabledUnselectedFillColor:
          disabledUnselectedFillColor ?? this.disabledUnselectedFillColor,
      borderColor: borderColor ?? this.borderColor,
      selectedFillColor: selectedFillColor ?? this.selectedFillColor,
      unselectedFillColor: unselectedFillColor ?? this.unselectedFillColor,
      borderRadius: borderRadius ?? this.borderRadius,
      borderThickness: borderThickness ?? this.borderThickness,
      elementStyle: elementStyle ?? this.elementStyle,
      errorStyle: errorStyle ?? this.errorStyle,
      innerBorderRadius: innerBorderRadius ?? this.innerBorderRadius,
      innerPadding: innerPadding ?? this.innerPadding,
      isChildrenAfter: isChildrenAfter ?? this.isChildrenAfter,
      isChildrenBefore: isChildrenBefore ?? this.isChildrenBefore,
      selectedIcon: selectedIcon ?? this.selectedIcon,
      shape: shape ?? this.shape,
      size: size ?? this.size,
      spacer: spacer ?? this.spacer,
      titleBuilder: titleBuilder ?? this.titleBuilder,
      titleDotBuilder: titleDotBuilder ?? this.titleDotBuilder,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWRadioMakeup = WRadioMakeup Function();
