// //.title
// // ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
// //
// // GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// // See: https://github.com/robmllze/xyz_gen
// //
// // ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
// //.title~

// // ignore: unused_import
// import '/_common.dart';

// // ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

// class WTagMakeup {
//   //
//   //
//   //

//   Color? backgroundColor;
//   TextStyle? textStyle;
//   EdgeInsets? padding;
//   EdgeInsets? margin;
//   BorderRadius? borderRadius;

//   //
//   //
//   //

//   WTagMakeup({
//     this.backgroundColor,
//     this.textStyle,
//     this.padding,
//     this.margin,
//     this.borderRadius,
//   });

//   //
//   //
//   //

//   WTagMakeup copyWith({
//     Color? backgroundColor,
//     TextStyle? textStyle,
//     EdgeInsets? padding,
//     EdgeInsets? margin,
//     BorderRadius? borderRadius,
//   }) {
//     return WTagMakeup(
//       backgroundColor: backgroundColor ?? this.backgroundColor,
//       textStyle: textStyle ?? this.textStyle,
//       padding: padding ?? this.padding,
//       margin: margin ?? this.margin,
//       borderRadius: borderRadius ?? this.borderRadius,
//     );
//   }
// }

// // ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

// typedef FWTagMakeup = WTagMakeup Function();

// const kWTagMakeupProperties = <String, String>{
//   'backgroundColor': 'Color?',
//   'textStyle': 'TextStyle?',
//   'padding': 'EdgeInsets?',
//   'margin': 'EdgeInsets?',
//   'borderRadius': 'BorderRadius?',
// };
