//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_switcher.dart'; // part '_w_switcher_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WSwitcherMakeup {
  //
  //
  //

  bool? isChildrenBefore;
  MaterialStateProperty<Color>? trackColor;
  MaterialStateProperty<Color>? overlayColor;
  MaterialStateProperty<Color>? thumbColor;
  Widget? spacer;

  //
  //
  //

  WSwitcherMakeup({
    this.isChildrenBefore,
    this.trackColor,
    this.overlayColor,
    this.thumbColor,
    this.spacer,
  });

  //
  //
  //

  WSwitcherMakeup copyWith({
    bool? isChildrenBefore,
    MaterialStateProperty<Color>? trackColor,
    MaterialStateProperty<Color>? overlayColor,
    MaterialStateProperty<Color>? thumbColor,
    Widget? spacer,
  }) {
    return WSwitcherMakeup(
      isChildrenBefore: isChildrenBefore ?? this.isChildrenBefore,
      trackColor: trackColor ?? this.trackColor,
      overlayColor: overlayColor ?? this.overlayColor,
      thumbColor: thumbColor ?? this.thumbColor,
      spacer: spacer ?? this.spacer,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWSwitcherMakeup = WSwitcherMakeup Function();
