//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'snack_bar_manager.dart'; // part '_snack_bar_manager_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class SnackBarManagerMakeup {
  //
  //
  //

  TextStyle? actionTextStyle;
  Color? backgroundColor;
  TextStyle? bodyTextStyle;
  BorderRadius? borderRadius;
  Icon? icon;
  WLoaderMakeup? loaderMakeup;
  List<BoxShadow>? shadow;

  //
  //
  //

  SnackBarManagerMakeup({
    this.actionTextStyle,
    this.backgroundColor,
    this.bodyTextStyle,
    this.borderRadius,
    this.icon,
    this.loaderMakeup,
    this.shadow,
  });

  //
  //
  //

  SnackBarManagerMakeup copyWith({
    TextStyle? actionTextStyle,
    Color? backgroundColor,
    TextStyle? bodyTextStyle,
    BorderRadius? borderRadius,
    Icon? icon,
    WLoaderMakeup? loaderMakeup,
    List<BoxShadow>? shadow,
  }) {
    return SnackBarManagerMakeup(
      actionTextStyle: actionTextStyle ?? this.actionTextStyle,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      bodyTextStyle: bodyTextStyle ?? this.bodyTextStyle,
      borderRadius: borderRadius ?? this.borderRadius,
      icon: icon ?? this.icon,
      loaderMakeup: loaderMakeup ?? this.loaderMakeup,
      shadow: shadow ?? this.shadow,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FSnackBarManagerMakeup = SnackBarManagerMakeup Function();
