//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_avatar_named.dart'; // part '_w_avatar_named_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WAvatarNamedMakeup {
  //
  //
  //

  Color? color;
  double? diameter;
  TextStyle? textStyle;

  //
  //
  //

  WAvatarNamedMakeup({
    this.color,
    this.diameter,
    this.textStyle,
  });

  //
  //
  //

  WAvatarNamedMakeup copyWith({
    Color? color,
    double? diameter,
    TextStyle? textStyle,
  }) {
    return WAvatarNamedMakeup(
      color: color ?? this.color,
      diameter: diameter ?? this.diameter,
      textStyle: textStyle ?? this.textStyle,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWAvatarNamedMakeup = WAvatarNamedMakeup Function();
