//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_button.dart'; // part '_w_button_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WButtonMakeup {
  //
  //
  //

  Color? color;
  double? defaultHeight;
  double? defaultWidth;
  WButtonMakeup? disabledMakeup;
  WLoaderMakeup? loaderMakeup;
  EdgeInsets? padding;
  List<BoxShadow>? shadow;
  RoundedRectangleBorder? shape;
  TextStyle? textStyle;

  //
  //
  //

  WButtonMakeup({
    this.color,
    this.defaultHeight,
    this.defaultWidth,
    this.disabledMakeup,
    this.loaderMakeup,
    this.padding,
    this.shadow,
    this.shape,
    this.textStyle,
  });

  //
  //
  //

  WButtonMakeup copyWith({
    Color? color,
    double? defaultHeight,
    double? defaultWidth,
    WButtonMakeup? disabledMakeup,
    WLoaderMakeup? loaderMakeup,
    EdgeInsets? padding,
    List<BoxShadow>? shadow,
    RoundedRectangleBorder? shape,
    TextStyle? textStyle,
  }) {
    return WButtonMakeup(
      color: color ?? this.color,
      defaultHeight: defaultHeight ?? this.defaultHeight,
      defaultWidth: defaultWidth ?? this.defaultWidth,
      disabledMakeup: disabledMakeup ?? this.disabledMakeup,
      loaderMakeup: loaderMakeup ?? this.loaderMakeup,
      padding: padding ?? this.padding,
      shadow: shadow ?? this.shadow,
      shape: shape ?? this.shape,
      textStyle: textStyle ?? this.textStyle,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWButtonMakeup = WButtonMakeup Function();
