//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'w_dialog.dart'; // part '_w_dialog_makeup.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class WDialogMakeup {
  //
  //
  //

  WIconMakeup? closeIconMakeup;
  BoxDecoration? decoration;
  double? maxHeight;
  double? maxWidth;
  TextStyle? messageTextStyle;
  Color? overlayColor;
  TextStyle? titleTextStyle;

  //
  //
  //

  WDialogMakeup({
    this.closeIconMakeup,
    this.decoration,
    this.maxHeight,
    this.maxWidth,
    this.messageTextStyle,
    this.overlayColor,
    this.titleTextStyle,
  });

  //
  //
  //

  WDialogMakeup copyWith({
    WIconMakeup? closeIconMakeup,
    BoxDecoration? decoration,
    double? maxHeight,
    double? maxWidth,
    TextStyle? messageTextStyle,
    Color? overlayColor,
    TextStyle? titleTextStyle,
  }) {
    return WDialogMakeup(
      closeIconMakeup: closeIconMakeup ?? this.closeIconMakeup,
      decoration: decoration ?? this.decoration,
      maxHeight: maxHeight ?? this.maxHeight,
      maxWidth: maxWidth ?? this.maxWidth,
      messageTextStyle: messageTextStyle ?? this.messageTextStyle,
      overlayColor: overlayColor ?? this.overlayColor,
      titleTextStyle: titleTextStyle ?? this.titleTextStyle,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FWDialogMakeup = WDialogMakeup Function();
